### ISSUE TITLE
Consider using #ifndef-style include guards instead of #pragma once

### ISSUE THREAD

**Issue by mackron** [lieff/minimp3#17]
I'm trying out minimp3 in one of my projects and the use of `#pragma once` instead of `#ifndef`-style include guards is a bit annoying:

1. For projects that are compiled as a single translation unit, `#pragma once` will not work when they need to keep the header and implementation sections separate (the header section will be included in one part, but due to `#pragma once`, the implementation section will never be able to be included in the same translation unit).
2. In the project I'm working on, being able to detect minimp3 at compile time with something like `#ifdef MINIMP3_H` or something similar would be really useful. (At the moment I'm using `#ifdef MINIMP3_MAX_SAMPLES_PER_FRAME` which feels a bit silly...)

Another quick note, it's not possible to compile minimp3 and stb_vorbis in the same translation unit because they both define an un-namespaced function called `get_bits()`. This is actually really inconvenient when writing a decoder abstraction and compiling as a single translation unit, which is what I'm working on.

Thanks for your work on this project!

**Comment by lieff** [comment]
Hmm. How about
```
#pragma once
#define MINIMP3_H
```
?

**Comment by mackron** [comment]
That will address my second point, but won't solve the first issue.

Consider this example - say I have some library with one .h file and one .c file: `my_lib.h` and `my_lib.c`. I may want to reference minimp3 in the .h file, but I don't want the _implementation_ of minimp3 to go there - I want that to go in `my_lib.c`. However, when something is using the my_lib library in another project, they may want to compile their project as a single translation unit by doing something like this:
```
#include "my_lib.h" // <-- #includes the header section of minimp3.

int main()
{
    my_lib_func();
    return 0;
}

#include "my_lib.c" // <-- #includes the implementation section of minimp3.
```
In the example above the implementation section will never get included because of the `#pragma once` from the header section.

In any case, this was just a suggestion - I've worked around it for my own purposes, but I feel like this could potentially be annoying for other people.

**Comment by lieff** [comment]
Well, main #pragma once feature is parsing speedup on over-include. But if we do not over-include - we do not get this feature and file is relatively small. I think it's safe to switch to #ifdef style.

**Comment by lieff** [comment]
Resolved in https://github.com/lieff/minimp3/commit/7fbf2be5634e4ca04113f44bf359a900b85b1d60

**Comment by OvermindDL1** [comment]
For note, most compilers give a parsing speedup on the `#ifdef` guards style as well (I think even visual studio does too nowadays?).

**Comment by OvermindDL1** [comment]
> So, without #pragma once, file must be completely readed/mmaped and parsed till the end.

Not everything though, when the guards happen at the begin and end of the file (excluding comments and whitespace) then it records that information based on the file location, and if the file location is `include`d again then it sees that the entire file was guarded and will prevent even reading the filesystem at all.

**Comment by lieff** [comment]
Yes, with no tokens before and after guard, plus guard define tracking and optimization is possible.
gcc really have this optimization:
test.h above:
```
[pid 15765] open("test.c", O_RDONLY|O_NOCTTY) = 3
[pid 15765] open("test.h", O_RDONLY|O_NOCTTY) = 4
[pid 15765] open("test.h", O_RDONLY|O_NOCTTY) = 4
[pid 15765] open("test.h", O_RDONLY)    = 4
```
If I remove tokens before/after and include twice:
```
[pid 15016] open("test2.c", O_RDONLY|O_NOCTTY) = 3
[pid 15016] open("test2.h", O_RDONLY|O_NOCTTY) = 4
[pid 15017] open("test2.o", O_RDWR|O_CREAT|O_TRUNC, 0666) = 3
```

**Comment by OvermindDL1** [comment]
Which further shows the non-standard `#pragma once` is unneeded especially as it is non-standard.  :-)

Though it doesn't hurt to include it in addition to include guards (the guards will at least work everywhere regardless), but it's still not necessary.

**Comment by mackron** [comment]
Regarding that earlier commit (7fbf2be), you don't want to wrap the _entire_ file in the `MINIMP3_H` include guard - it should only wrap the header section. The implementation section should be guarded with `MINIMP3_IMPLEMENTION`. This is the standard way all single-file libraries I've ever used and built work.

Any compile time inefficiencies between `#pragma once` and `#ifndef MINIMP3_H` will be negligible and virtually unnoticeable for a project of this size.

**Comment by lieff** [comment]
Well, bye-bye optimization
```
[pid  3358] open("minimp3_test.c", O_RDONLY|O_NOCTTY) = 3
[pid  3358] open("minimp3.h", O_RDONLY|O_NOCTTY) = 4
[pid  3358] open("minimp3.h", O_RDONLY|O_NOCTTY) = 4
[pid  3359] open("minimp3_test.o", O_RDWR|O_CREAT|O_TRUNC, 0666) = 3
```
https://github.com/lieff/minimp3/commit/05289fcecaa18cf211e260333ed383fbdc9fdc52

**Comment by mackron** [comment]
That's the way! 👍 

I have some much bigger single-file libraries than minimp3 and compile times have never been an issue for me in practice. In my experience, it's usually the giant files like `windows.h` which in turn `#include` a seemingly never ending chain of other files that cause the real compile time issues.

Thanks for your work on minimp3!

**Comment by lieff** [comment]
I'm just from DSP etc :) sometimes I'm nervous even if it's few instructions, clock-ticks or bytes.

**Comment by OvermindDL1** [comment]
@mackron You can always concat all header and source files into a single file pre-build in the build system.  CMake has popular ways of doing that, just enable a single flag when you have the script in the project and it will pre-`cat` them all together in the proper order based on dependencies, and then pass that single massive file to the compiler.  It takes more memory (a lot more) but it can bring a 50 minutes compile time down to 5 minutes easy (again, assuming you have the RAM).

And yeah, even in an inefficient case the header parsing is utterly trivial compared to actual compilation.  :-)

**Comment by mackron** [comment]
@OvermindDL1 In my multi-file projects I just include every .h and .c file into the main.c file, in which case that file essentially becomes the build file. Then compiling becomes a simple matter of running a trivial build script against GCC/Clang/whatever directly without the need for any external dependency like CMake.

@lieff These changes you made are good so I'm happy for you to close this issue if you like.

**Comment by OvermindDL1** [comment]
> @OvermindDL1 In my multi-file projects I just include every .h and .c file into the main.c file, in which case that file essentially becomes the build file. Then compiling becomes a simple matter of running a trivial build script against GCC/Clang/whatever directly without the need for any external dependency like CMake.

Heh, that is quite a popular style yeah.  It is not as efficient with few files, but with 'huge' projects it can save *substantial* amounts of compiling time too.  :-)

**Comment by lieff** [comment]
Thanks :) closing then.
